[versions]
kotlin = "1.9.10"
android-gradle-plugin = "8.1.4"
coroutines = "1.7.3"
androidx-lifecycle = "2.7.0"
androidx-startup = "1.1.1"
dokka = "1.9.10"
maven-publish = "0.25.3"
sqlite = "2.4.0"
kotlinx-serialization = "1.6.2"
japicmp = "0.4.1"
kotlinx-datetime = "0.4.0"
japicmp-gradle = "0.3.1"
spotless = "6.25.0"
detekt = "1.23.4"
ktlint = "0.50.0"

[libraries]
# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

# AndroidX
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }

# SQLite
sqlite-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version = "3.43.2.2" }

# Testing
junit = { group = "junit", name = "junit", version = "4.13.2" }
mockito-core = { group = "org.mockito", name = "mockito-core", version = "5.7.0" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# API Compatibility
japicmp = { group = "me.champeau.japicmp", name = "japicmp", version.ref = "japicmp" }
japicmp-gradle = { group = "me.champeau.japicmp", name = "japicmp-gradle", version.ref = "japicmp-gradle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
